"""
Django settings for babys project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 项目路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 密钥配置
SECRET_KEY = 'ba134-s4ivljdy$4+&$nl7)52db1%nq%hoo38*6+fxy3_4k)_g'

# SECURITY WARNING: don't run with debug turned on in production!
# 调试模式
DEBUG = True

# 域名访问权限
ALLOWED_HOSTS = []


# Application definition
# 注册app列表
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'commodity',
    'shopper',
]

# 中间件
MIDDLEWARE = [
    # 内置的安全机智，保护用户和网站的通信安全
    'django.middleware.security.SecurityMiddleware',
    # 会话session功能
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 添加中间件LocaleMiddleware
    # 国际化和本地化功能
    'django.middleware.locale.LocaleMiddleware',
    # 处理请求信息，规范化请求内容
    'django.middleware.common.CommonMiddleware',
    # 开去CSRF防护功能
    'django.middleware.csrf.CsrfViewMiddleware',
    # 开启内置的用户认证系统
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 开启内置的信息提示功能
    'django.contrib.messages.middleware.MessageMiddleware',
    # 防止恶意程序的单机劫持
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 路由入口
ROOT_URLCONF = 'babys.urls'

# 模版配置和存放位置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI配置
WSGI_APPLICATION = 'babys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# 数据库配置
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'babys',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

# 内置auth认真功能配置
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# 国际化配置，时间，语言
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# 静态资源配置
STATIC_URL = '/static/'

#  添加并设置配置属性 STATICFILES_DIRS
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'pstatic'),
)

# 配置媒体资源
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
